name: Example workflow with OX Security Scan
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - master
      - development
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run OX Security Scan to check for vulnerabilities
        with:
          ox_api_key: ox_PZWcICSB@6e5orBQtBoa8K60JpT1MoTwtD1Q
        uses: oxsecurity/ox-security-scan@main
